ARG BUILD_FROM=node:18-alpine
FROM $BUILD_FROM

ENV NODE_EXTRA_CA_CERTS=/usr/src/app/controlmyspa-ca-fullchain.pem

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

CMD [ "node", "app.js" ]
